### ISSUE TITLE
"CWE_Number" column is duplicated

### ISSUE THREAD

**Issue by RichardMelito** [icsadvprj/ICS-Advisory-Project#6]
The "CWE_Number" column is duplicated in the current master file.
![image](https://github.com/icsadvprj/ICS-Advisory-Project/assets/69733336/4b9a5c2b-1ca4-496a-8ed8-01ca0808a4b5)

**Comment by icsadvprj** [comment]
Thank you! We have removed the duplicated "CWE_Number" column in the CISA_ICS_ADV_Master.csv.
